---
- name: Include tasks to find PVE node with most free memory.
  ansible.builtin.include_tasks: max-free.yml
  when: cloud_init_find_pm_host

- name: Set KVM facts.
  ansible.builtin.set_fact:
    cloud_init_ipconfig0_list: "{{
      (['ip=' + creator_item.ip] if creator_item.ip is defined else []) +
      (['gw=' + cloud_init_network_gw] if (cloud_init_network_gw is defined and
        creator_item.ip is defined and creator_item.ip != 'dhcp') else []) +
      (['ip6=' + creator_item.ip6] if creator_item.ip6 is defined else
        (['ip6=' + cloud_init_network_ipv6_ula_prefix |
          ansible.utils.ipmath(creator_item_random_number) +
          '/%s' | format(cloud_init_network_ipv6_ula_prefix | ansible.utils.ipaddr('prefix'))]
        if cloud_init_network_ipv6_ula_prefix is defined else [])) +
      (['gw6=' + cloud_init_network_gw6] if (cloud_init_network_gw6 is defined and
        (cloud_init_network_ipv6_ula_prefix is defined or
        (creator_item.ip6 is defined and creator_item.ip6 != 'auto'))) else []) }}"

    cloud_init_ipconfig1_list: "{{
      (['ip=' + creator_item.net1_ip] if creator_item.net1_ip is defined else []) +
      (['gw=' + cloud_init_network1_gw] if (cloud_init_network1_gw is defined and
        creator_item.net1_ip is defined and creator_item.net1_ip != 'dhcp') else []) +
      (['ip6=' + creator_item.net1_ip6] if creator_item.net1_ip6 is defined else
        (['ip6=' + cloud_init_network1_ipv6_ula_prefix |
          ansible.utils.ipmath(creator_item_random_number) +
          '/%s' | format(cloud_init_network1_ipv6_ula_prefix | ansible.utils.ipaddr('prefix'))]
        if cloud_init_network1_ipv6_ula_prefix is defined else [])) +
      (['gw6=' + cloud_init_network1_gw6] if (cloud_init_network1_gw6 is defined and
        (cloud_init_network1_ipv6_ula_prefix is defined or
        (creator_item.net1_ip6 is defined and creator_item.net1_ip6 != 'auto'))) else []) }}"

    cloud_init_ipconfig2_list: "{{
      (['ip=' + creator_item.net2_ip] if creator_item.net2_ip is defined else []) +
      (['gw=' + cloud_init_network2_gw] if (cloud_init_network2_gw is defined and
        creator_item.net2_ip is defined and creator_item.net2_ip != 'dhcp') else []) +
      (['ip6=' + creator_item.net2_ip6] if creator_item.net2_ip6 is defined else
        (['ip6=' + cloud_init_network2_ipv6_ula_prefix |
          ansible.utils.ipmath(creator_item_random_number) +
          '/%s' | format(cloud_init_network2_ipv6_ula_prefix | ansible.utils.ipaddr('prefix'))]
        if cloud_init_network2_ipv6_ula_prefix is defined else [])) +
      (['gw6=' + cloud_init_network2_gw6] if (cloud_init_network2_gw6 is defined and
        (cloud_init_network2_ipv6_ula_prefix is defined or
        (creator_item.net2_ip6 is defined and creator_item.net2_ip6 != 'auto'))) else []) }}"

    cloud_init_ipconfig3_list: "{{
      (['ip=' + creator_item.net3_ip] if creator_item.net3_ip is defined else []) +
      (['gw=' + cloud_init_network3_gw] if (cloud_init_network3_gw is defined and
        creator_item.net3_ip is defined and creator_item.net3_ip != 'dhcp') else []) +
      (['ip6=' + creator_item.net3_ip6] if creator_item.net3_ip6 is defined else
        (['ip6=' + cloud_init_network3_ipv6_ula_prefix |
          ansible.utils.ipmath(creator_item_random_number) +
          '/%s' | format(cloud_init_network3_ipv6_ula_prefix | ansible.utils.ipaddr('prefix'))]
        if cloud_init_network3_ipv6_ula_prefix is defined else [])) +
      (['gw6=' + cloud_init_network3_gw6] if (cloud_init_network3_gw6 is defined and
        (cloud_init_network3_ipv6_ula_prefix is defined or
        (creator_item.net3_ip6 is defined and creator_item.net3_ip6 != 'auto'))) else []) }}"

- name: "Create Virtual Machine '{{ creator_item.name }}'."
  community.proxmox.proxmox_kvm:
    api_host: "{{ cloud_init_pm_api_host }}"
    api_user: "{{ cloud_init_pm_api_user }}"
    api_token_id: "{{ cloud_init_pm_api_token_name }}"
    api_token_secret: "{{ cloud_init_pm_api_token_secret }}"

    agent: "{{ cloud_init_agent }}"
    cicustom: "{{ creator_item.custom | default(cloud_init_custom) | default(omit) }}"
    cores: "{{ cloud_init_ctrl_cores if generated_vm_is_controller else cloud_init_work_cores }}"
    cpu: "{{ cloud_init_cpu | default(omit) }}"
    description: "{{ creator_item.description | default(omit) }}"
    ide:
      ide2: "{{ cloud_init_disk_storage }}:cloudinit"
    ipconfig:
      ipconfig0: "{{ cloud_init_ipconfig0_list | join(',') if
        cloud_init_ipconfig0_list | length > 0 else omit }}"
      ipconfig1: "{{ cloud_init_ipconfig1_list | join(',') if
        cloud_init_ipconfig1_list | length > 0 else omit }}"
      ipconfig2: "{{ cloud_init_ipconfig2_list | join(',') if
        cloud_init_ipconfig2_list | length > 0 else omit }}"
      ipconfig3: "{{ cloud_init_ipconfig3_list | join(',') if
        cloud_init_ipconfig3_list | length > 0 else omit }}"
    memory: "{{ cloud_init_ctrl_memory if generated_vm_is_controller else cloud_init_work_memory }}"
    name: "{{ creator_item.name }}"
    nameservers: "{{ cloud_init_nameservers }}"
    net:
      net0: "virtio,bridge={{ cloud_init_network_bridge }}{{ cloud_init_var_vlan }}"
      net1: "{{ 'virtio,bridge=%s%s' | format(cloud_init_network1_bridge, cloud_init_var_vlan1)
        if cloud_init_ipconfig1_list | length > 0 else omit }}"
      net2: "{{ 'virtio,bridge=%s%s' | format(cloud_init_network2_bridge, cloud_init_var_vlan2)
        if cloud_init_ipconfig2_list | length > 0 else omit }}"
      net3: "{{ 'virtio,bridge=%s%s' | format(cloud_init_network3_bridge, cloud_init_var_vlan3)
        if cloud_init_ipconfig3_list | length > 0 else omit }}"
    node: "{{ creator_item.pm_host | default(cloud_init_pm_host) }}"
    searchdomains: "{{ cloud_init_searchdomains }}"
    serial:
      serial0: "socket"
    scsi:
      scsi0: "{{ creator_item.storage | default(cloud_init_storage)
        }}:0,format=raw,import-from={{ cloud_init_image_storage }}:{{
        cloud_init_image_storage_content }}/{{ cloud_init_image }}"
    scsihw: "virtio-scsi-pci"
    sshkeys: "{{ proxmox_client_sshkeys | default(cloud_init_sshkeys) | default(omit) }}"
    sockets: "{{ cloud_init_ctrl_sockets if generated_vm_is_controller else cloud_init_work_sockets }}"
    state: "present"
    storage: "{{ creator_item.storage | default(cloud_init_storage) }}"
    tags: "{{ creator_item.tags | default(cloud_init_tags) }}"
    timeout: 300
    vga: "serial0"
    vmid: "{{ cloud_init_vlan_tag + creator_item.vmid if cloud_init_vlan_tag is defined and
      creator_item.vmid is defined else creator_item.vmid if creator_item.vmid is defined else omit }}"
  notify: Cloud init inventory refresh
  register: cloud_init_creator_qemu_vm

- name: "Resize the disk for the Virtual Machine '{{ creator_item.name }}'."
  community.proxmox.proxmox_disk:
    api_host: "{{ cloud_init_pm_api_host }}"
    api_user: "{{ cloud_init_pm_api_user }}"
    api_token_id: "{{ cloud_init_pm_api_token_name }}"
    api_token_secret: "{{ cloud_init_pm_api_token_secret }}"

    disk: "scsi0"
    size: "{{ cloud_init_ctrl_disk_size if generated_vm_is_controller else cloud_init_work_disk_size }}"
    state: "resized"
    vmid: "{{ cloud_init_creator_qemu_vm.vmid }}"

- name: "Start the Virtual Machine '{{ creator_item.name }}'."
  community.proxmox.proxmox_kvm:
    api_host: "{{ cloud_init_pm_api_host }}"
    api_user: "{{ cloud_init_pm_api_user }}"
    api_token_id: "{{ cloud_init_pm_api_token_name }}"
    api_token_secret: "{{ cloud_init_pm_api_token_secret }}"
    state: "started"
    vmid: "{{ cloud_init_creator_qemu_vm.vmid }}"
  delay: 2
  register: cloud_init_creator_qemu_start
  until: not cloud_init_creator_qemu_start.failed
