---
- name: Make sure that SSH Keys are set.
  ansible.builtin.assert:
    that: lxc_sshkeys is defined
    quiet: true

- name: Make sure that any required constuct values are set.
  ansible.builtin.assert:
    that:
      - lxc_construct_cidr_start is defined
      - lxc_construct_hosts | length > 0
    quiet: true
  when: lxc_construct_containers > 0

- name: Construct containers list
  ansible.builtin.set_fact:
    cts:
      name: "{{ lxc_construct_container_prefix }}{{ item + 1 }}"
      ip: "{{ lxc_construct_cidr_start | ansible.utils.ipmath(item)
        }}/{{ lxc_construct_cidr_start | split('/') | last }}"
      ip6: "{{ '%s/%s' | format(
        lxc_construct_cidr6_start | default('::/0') | ansible.utils.ipmath(item),
        lxc_construct_cidr6_start| split('/') | last)
        if lxc_construct_cidr6_start is defined else omit }}"
      pm_host: "{{ omit if not lxc_construct_hosts else lxc_construct_hosts[item % lxc_construct_hosts | length] }}"
      tags: "{{ lxc_construct_ct0_tags if lxc_construct_ct0_tags and item < 1 else
        omit }}"
      vmid: "{{ '%03d' | format(lxc_construct_vmid_start + item)
        if lxc_construct_vmid_start is defined else omit }}"
  register: generated_lxcs
  loop: "{{ range(0, lxc_construct_containers) | list }}"

- name: Combine constructed containers and containers.
  ansible.builtin.set_fact:
    combined_lxcs: "{{ lxc_cts + generated_lxcs.results
      | map(attribute='ansible_facts.cts') }}"

- name: Include the creation tasks.
  ansible.builtin.include_tasks: creator.yml
  loop: "{{ combined_lxcs }}"
  loop_control:
    loop_var: creator_item

- name: Flush handlers.
  meta: flush_handlers

- name: Scan for ssh-hostkeys
  ansible.builtin.command:
    cmd: "/usr/bin/ssh-keyscan {{ hostvars[item]['ansible_host'] }}"
  changed_when: false
  ignore_errors: true
  register: lxc_keyscan_cmd
  loop: "{{ combined_lxcs | map(attribute='name') }}"
  loop_control:
    label: "{{ item }}: {{ hostvars[item]['ansible_host'] }}"
  until: not lxc_keyscan_cmd.failed
  when: lxc_update_known_hosts is true

- name: Add hostkeys to known_hosts
  ansible.builtin.lineinfile:
    path: ~/.ssh/known_hosts
    regexp: "^{{ item.split()[:2] | join(' ') }}"
    line: "{{ item }}"
  loop: "{{ lxc_keyscan_cmd.results | map(attribute='stdout_lines') | flatten }}"
  loop_control:
    label: "{{ item.split()[:2] | join(' ') }}"
  when:
    - lxc_update_known_hosts is true
    - item[:1] != '#'

- name: Wait for the new systems to be accessible.
  ansible.builtin.wait_for_connection:
  delegate_to: "{{ item.name }}"
  loop: "{{ combined_lxcs }}"
  loop_control:
    label: "{{ item.name }}"
  when: lxc_bypass_wait_for_connection is true
