---
# tasks file for lxc

- name: Construct containers list
  ansible.builtin.set_fact:
    cts:
      name: "{{ lxc_construct_container_prefix }}{{ item + 1 }}"
      ip: "{{ lxc_construct_cidr_start | ansible.utils.ipmath(item)
        }}/{{ lxc_construct_cidr_start | split('/') | last }}"
      ip6: "{{ omit if lxc_construct_cidr6_start == ''
        else '%s/%s' | format(lxc_construct_cidr6_start | default('0.0.0.0/24')
        | ansible.utils.ipmath(item), lxc_construct_cidr6_start | split('/') | last)
        }}"
      pm_host: "{{ lxc_construct_hosts[item % lxc_construct_hosts | length] }}"
      tags: "{{ lxc_construct_ct0_tags if lxc_construct_ct0_tags and item < 1 else
        omit }}"
      vmid: "{{ '%03d' | format(lxc_construct_vmid_start + item) }}"
  register: generated_lxcs
  loop: "{{ range(0, lxc_construct_containers) | list }}"

- name: Combine constructed containers and containers.
  ansible.builtin.set_fact:
    combined_lxcs: "{{ lxc_cts + generated_lxcs.results
      | map(attribute='ansible_facts.cts') }}"

- name: Create LXC container.
  community.general.proxmox:
    api_host: "{{ lxc_pm_api_host }}"
    api_user: "{{ lxc_pm_api_user }}"
    api_token_id: "{{ lxc_pm_api_token_name }}"
    api_token_secret: "{{ lxc_pm_api_token_secret }}"

    cores: "{{ lxc_cores }}"
    cpus: "{{ lxc_cpus }}"
    disk: "{{ item.storage | default(lxc_storage) }}:{{ lxc_disk_size }}"
    hostname: "{{ item.name }}"
    memory: "{{ lxc_memory }}"
    nameserver: "{{ ' '.join(lxc_nameservers) }}"
    netif:
      net0: "name=eth0,bridge={{ lxc_network_bridge }},ip={{ item.ip | default('dhcp') }}{{ lxc_net0_gw
        }}{{ ',ip6=' + item.ip6 + lxc_net0_gw6 if item.ip6 is defined }}{{ lxc_net0_vlan }}"
    node: "{{ item.pm_host | default(lxc_pm_host) }}"
    ostemplate: "{{ lxc_template_storage }}:vztmpl/{{ lxc_template }}"
    pubkey: "{{ omit if lxc_sshkeys == '' else lxc_sshkeys }}"
    searchdomain: "{{ ' '.join(lxc_searchdomains) }}"
    state: "present"
    storage: "{{ item.storage | default(lxc_storage) }}"
    swap: "{{ lxc_swap }}"
    tags: "{{ lxc_tags + item.tags | default([]) }}"
    unprivileged: "{{ lxc_unprivileged }}"
    vmid: "{{ item.vmid }}"
  loop: "{{ combined_lxcs }}"

- name: Start LXC container
  community.general.proxmox:
    api_host: "{{ lxc_pm_api_host }}"
    api_user: "{{ lxc_pm_api_user }}"
    api_token_id: "{{ lxc_pm_api_token_name }}"
    api_token_secret: "{{ lxc_pm_api_token_secret }}"

    state: "started"
    unprivileged: "{{ lxc_unprivileged }}"
    vmid: "{{ item.vmid }}"
  loop: "{{ combined_lxcs }}"
  loop_control:
    label: "{{ item.name }}"
