---
# Look at the README.md file for details on the variables.
# Not all the variables used have default values shown here.

# The values here must be set to use an "API Token".
# The user and token must also have the permissions needed to perform all tasks.
lxc_pm_api_host: 'proxmox_master'
lxc_pm_api_user: 'devops@pve'
lxc_pm_api_token_name: 'ansible'

# In order to protect the API Token Secret, it will by default
# be read from a file under the calling users $HOME directory.
# For example, using the above `lxc_pm_api_user` and `pm_api_token` will produce
# the file `$HOME/.pve_tokens/devops-pve-ansible.token`.
lxc_secrets_dir: "{{ lookup('env', 'HOME') }}/.pve_tokens"
lxc_pm_api_token_file: "{{ lxc_pm_api_user | replace('@', '-')
  }}-{{ lxc_pm_api_token_name }}.token"

lxc_ansible_host: false
lxc_ansible_host_vars_paths:
  - "{{ ansible_inventory_sources }}"
  - "{{ ansible_inventory_sources[0] | dirname }}"
lxc_ansible_host_vars_dir: "{{ lookup('ansible.builtin.first_found',
  'host_vars',
  paths=lxc_ansible_host_vars_paths) }}"
lxc_ansible_inventory_refresh: false
lxc_bypass_wait_for_connection: false
lxc_construct_container_prefix: "new_container"
lxc_construct_containers: 0
lxc_construct_ct0_tags: []
lxc_construct_hosts: []
lxc_cores: "4"
lxc_cpus: "1"

lxc_cts: []

lxc_disk_size: "9"
lxc_find_pm_host: false
lxc_features: []
lxc_memory: "1024"
lxc_nameservers: []
lxc_network_bridge: "vmbr0"
lxc_pm_host: "{{ lxc_pm_api_host }}"
lxc_searchdomains: []
lxc_storage: "local-thin"
lxc_swap: 0
lxc_tags: []
lxc_template: "ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
lxc_template_storage: 'local'
lxc_unprivileged: true
lxc_update_known_hosts: true
