---
# The values here must be set to use an "API Token".
# The user and token must also have the permissions needed to perform all tasks.
lxc_pm_api_host: 'proxmox_master'
lxc_pm_api_user: 'devops@pve'
lxc_pm_api_token_name: 'ansible'

# In order to protect the API Token Secret, it will by default
# be read from a file under the calling users $HOME directory.
# For example, using the above `lxc_pm_api_user` and `pm_api_token` will produce
# the file `$HOME/.pve_tokens/devops-pve-ansible.token`.
lxc_secrets_dir: "{{ lookup('env', 'HOME') }}/.pve_tokens"
lxc_pm_api_token_file: "{{ lxc_pm_api_user | replace('@', '-')
  }}-{{ lxc_pm_api_token_name }}.token"

# By default, calling this role will not create any containers.
# You must either provide a `containers` list or
# set multiple `lxc_construct_*` values.
# Both of these can be set and will create all the containers desired but
# may also confuse anyone reading your playbook and is discouraged.

# Set the `ansible_host` variable in the `host_vars` file.
lxc_ansible_host: false

# The paths on the control host where the `host_vars` directory can be found.
# The default will look next to one of the Inventory sources and
# then in the parent directory of the first Inventory source.
# Set this to any other paths if you use a `host_vars` in a unique location.
lxc_ansible_host_vars_paths:
  - "{{ ansible_inventory_sources }}"
  - "{{ ansible_inventory_sources[0] | dirname }}"

# Directory containing the individual host_vars files.
lxc_ansible_host_vars_dir: "{{ lookup('ansible.builtin.first_found',
  'host_vars',
  paths=lxc_ansible_host_vars_paths) }}"

# Perform a refresh_inventory after
# 1) creating an LXC container
# 2) starting an LXC container and the local 'host_vars' was changed.
lxc_ansible_inventory_refresh: "{{ lxc_ansible_host }}"

# Providing a list of dicts for the containers to create.
# Each list item must contain a set of required and possibly optional keys.
# Required list item keys:
# - name: The name of the containers and becomes the hostname
# - ip: Static IPv4 CIDR address
# - vmid: The VMID for each container
#         Automatically selecting the next available value is not supported.
#         The `lxc_vlan_tag` is prepended to this value.
#         Each MUST be unique within the Datacenter.
# Optional list item keys:
# - pm_host: Override the global value
# - tags: Override the global value
# - ip6: Static IPv6 CIDR address (default: unset)
# - storage: Override the global value
lxc_cts: []

# Providing values to construct the list of containers to create.
# The starting IPv4 address in CIDR notation
lxc_construct_cidr_start: ""

# The starting IPv6 address in CIDR notation, disabled when not set
lxc_construct_cidr6_start: ""

# Begining part of each control node hostname, a sequencial number is appended.
lxc_construct_container_prefix: "new_container"

# The number of containers to create
lxc_construct_containers: 0

# Additional tags to add to the first container in the constructed list.
lxc_construct_ct0_tags: []

# A list of Proxmox hosts across which the containers will be created.
# The VMs are created by looping over this list, putting one on each host
# listed in a round-robin fashion.
lxc_construct_hosts: []

# The VMID of the first container created and incremented for each subsequent
# container.
lxc_construct_vmid_start: 0

# Default values for the LXC containers created.

# The number of CPU cores for each container.
lxc_cores: "4"

# The number of CPUs (or sockets) for each container.
lxc_cpus: "1"

# The size of the root disk for each container (in GB).
lxc_disk_size: "9"

# A list of features, current possible features are;
# `force_rw_sys`, `fuse`, `keyctl`, `mknod`, `mount` and `nesting`.
lxc_features: []

# The amount of memory for each container (in KB).
lxc_memory: "1024"

# A list of name servers for the containers.
lxc_nameservers: []

# The network bridge to be used for each container.
# All Proxmox clusters contain a `vmbr0` network bridge by default.
lxc_network_bridge: "vmbr0"

# The role only supports creating all containers on the same subnet and
# using the same default gateway.
lxc_network_gw: ''

# The Proxmox Host on which containers are created by default.
# Override this for individual items in the `containers` list.
# See the comment for `lxc_construct_hosts` above for a construct.
lxc_pm_host: "{{ lxc_pm_api_host }}"

# A list of search domains for DNS lookups.
lxc_searchdomains: []

# WARNING! There is no default value here,
# and leaving this empty will result in containers to which you cannot login!
lxc_sshkeys: ''

# Where to place the disk for each container created.
# This storage _must_ exist on each host on which containers are created and
# be configured to support the "Container" content type.
# For a cluster, consider using shared storage for migration support.
# Common values include: `local-thin`, `local-zfs` and `ceph0`.
lxc_storage: "local-thin"

# The amount of swap to allocate for each container.
lxc_swap: 0

# A list of Proxmox tags to assign all the containers created.
lxc_tags: []

# The Template name from which to create the LXC containers.
lxc_template: "ubuntu-22.04-standard_22.04-1_amd64.tar.zst"

# The Datacenter storage containing the template above.
lxc_template_storage: 'local'

# The unprevileged setting for all containers.
lxc_unprivileged: true

# Make sure this is set to '', if there is no VLAN.
# This value will also be prepended to all VMID values.
lxc_vlan_tag: ''
