---
# Look at the README.md file for details on the variables.
# Not all the variables used have default values shown here.

# The values here must be set to use an "API Token".
# The user and token must also have the permissions needed to perform all tasks.
cloud_init_pm_api_host: 'proxmox_master'
cloud_init_pm_api_user: 'devops@pve'
cloud_init_pm_api_token_name: 'ansible'

# In order to protect the API Token Secret, it will by default
# be read from a file under the calling users $HOME directory on the control host.
# For example, using the above `cloud_init_pm_api_user` and `pm_api_token`
# will produce the file `$HOME/.pve_tokens/devops-pve-ansible.token`.
cloud_init_secrets_dir: "{{ lookup('env', 'HOME') }}/.pve_tokens"
cloud_init_pm_api_token_file: "{{ cloud_init_pm_api_user | replace('@', '-')
  }}-{{ cloud_init_pm_api_token_name }}.token"

cloud_init_agent: false
cloud_init_ansible_host: false
cloud_init_ansible_host_vars_paths:
  - "{{ ansible_inventory_sources }}"
  - "{{ ansible_inventory_sources[0] | dirname }}"
cloud_init_ansible_host_vars_dir: "{{ lookup('ansible.builtin.first_found',
  'host_vars',
  paths=cloud_init_ansible_host_vars_paths) }}"
cloud_init_ansible_inventory_refresh: "{{ cloud_init_ansible_host }}"
cloud_init_bypass_wait_for_connection: false

cloud_init_construct_controllers: 0
cloud_init_construct_ctrl_prefix: "ctrl"
cloud_init_construct_hosts: []
cloud_init_construct_work_prefix: "work"
cloud_init_construct_workers: 0

cloud_init_ctrl_cores: '4'
cloud_init_ctrl_disk_size: '12G'
cloud_init_ctrl_memory: '8192'
cloud_init_ctrl_sockets: '1'
cloud_init_ctrl_tags: ["control", "{{ cloud_init_k8s_tag }}"]

cloud_init_disk_storage: 'local'
cloud_init_find_pm_host: false
cloud_init_genesis_tags: "control,genesis,{{ cloud_init_k8s_tag }}"
cloud_init_image: ubuntu-24.04-server.qcow2
cloud_init_image_storage: local
cloud_init_k8s_tag: 'k8s'
cloud_init_nameservers: []
cloud_init_network_bridge: 'vmbr0'
cloud_init_network1_bridge: 'vmbr1'
cloud_init_network2_bridge: 'vmbr2'
cloud_init_network3_bridge: 'vmbr3'
cloud_init_pm_host: "{{ cloud_init_pm_api_host }}"
cloud_init_searchdomains: []
cloud_init_storage: 'local-thin'
cloud_init_tags: []
cloud_init_update_known_hosts: true
cloud_init_vmid: '00'

cloud_init_vms: []

cloud_init_work_cores: '2'
cloud_init_work_disk_size: '12G'
cloud_init_work_memory: '8192'
cloud_init_work_sockets: '1'
cloud_init_work_tags: ["{{ cloud_init_k8s_tag }}", "worker"]
