---
# vars file for cloud_init

# Be careful about directly setting this as it may result in the token secret value being leaked in various ways.
cloud_init_pm_api_token_secret: "{{ lookup('file', cloud_init_secrets_dir + '/' + cloud_init_pm_api_token_file) }}"
cloud_init_pm_default_api_token_file: "{{ cloud_init_pm_api_user | replace('@', '-')
  }}-{{ cloud_init_pm_api_token_name }}.token"

# These are not meant to be set by the calling playbook.
cloud_init_var_vlan: "{{ ',tag=' + cloud_init_vlan_tag if cloud_init_vlan_tag is defined else '' }}"
cloud_init_var_vlan1: "{{ ',tag=' + cloud_init_vlan1_tag if cloud_init_vlan1_tag is defined else '' }}"
cloud_init_var_vlan2: "{{ ',tag=' + cloud_init_vlan2_tag if cloud_init_vlan2_tag is defined else '' }}"
cloud_init_var_vlan3: "{{ ',tag=' + cloud_init_vlan3_tag if cloud_init_vlan3_tag is defined else '' }}"
